
//continents
export const GET_CONTINENTS= 'GET_CONTINENTS';
export const GET_CONTINENTS_PENDING = 'GET_CONTINENTS_PENDING'; 
export const GET_CONTINENTS_REJECTED = 'GET_CONTINENTS_REJECTED'; 
export const GET_CONTINENTS_FULFILLED = 'GET_CONTINENTS_FULFILLED'; 

//users

export const GET_USER = 'GET_USER';